theme: jekyll-theme-slate
title: Lab 8
description: Create lab file and initialize Node.js folder, Install node-fetch package, Add fastify starter code, Add fastify and node-fetch require statements, Fetch JSONPlaceholder data
